---
# tasks file for java

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - java

- include_tasks: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - java

- include_tasks: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - java
