---
# tasks file for java (Ubuntu specific)

- name: Add OpenJDK-R Java PPA
  become: yes
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present
  when: java_implementation == "openjdk" and java_openjdk_use_ppa
  tags:
    - java

- name: Install OpenJDK Java
  become: yes
  apt:
    name: openjdk-{{ java_openjdk_version }}-jdk
    update_cache: yes
    state: present
  when: java_implementation == "openjdk" and not java_openjdk_jre_only|bool
  tags:
    - java

- name: Install OpenJDK Java Runtime Environment only
  become: yes
  apt:
    name: openjdk-{{ java_openjdk_version }}-jre{{ java_openjdk_headless|bool|ternary('-headless','') }}
    update_cache: yes
    state: present
  when: java_implementation == "openjdk" and java_openjdk_jre_only|bool
  tags:
    - java

- name: Add Web Upd8 Oracle Java PPA
  become: yes
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present
  when: java_implementation == "oracle"
  tags:
    - java

- name: Accept Oracle Java license
  become: yes
  debconf:
    name: oracle-java{{ java_oracle_version }}-installer
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'
  when: java_implementation == "oracle"
  tags:
    - java

- name: Install Oracle Java
  become: yes
  apt:
    name: oracle-java{{ java_oracle_version }}-installer
    update_cache: yes
    state: present
  when: java_implementation == "oracle"
  tags:
    - java

- name: Install Oracle JCE Policy
  become: yes
  apt:
    name: oracle-java{{ java_oracle_version }}-unlimited-jce-policy
    update_cache: yes
    state: present
  when: java_implementation == "oracle" and java_oracle_install_jce_policy
  tags:
    - java
